select*from dbo.CLIENTES
select*from dbo.COMERCIALES
select*from dbo.VENTAS_TOTALES
select*from dbo.V_Semana

ALTER TABLE dbo.VENTAS
DROP COLUMN CANAL;
ALTER TABLE dbo.VENTAS_TOTALES
ALTER COLUMN AÑO INT;
ALTER TABLE dbo.VENTAS_TOTALES
ALTER COLUMN VENDIDO_POR NVARCHAR(255);
ALTER TABLE dbo.VENTAS_TOTALES
ALTER COLUMN MES NVARCHAR(255);
ALTER TABLE dbo.V_Semana
ALTER COLUMN REFERENCIA NVARCHAR(255);
UPDATE dbo.VENTAS_TOTALES
SET FECHA = CAST(FECHA AS DATE);
UPDATE dbo.V_Semana
SET FECHA = CAST(FECHA AS DATE);
-- Por si quiero borrar algo:
DELETE FROM dbo.VENTAS_TOTALES
WHERE FACTURA = 'grs-1';

select CEILING(DATEPART(MONTH, FECHA) / 3.0) AS xyz from dbo.V_Semana

-- Paso 1 Actualizamos los datos de las nuevas columnas:
ALTER TABLE dbo.V_Semana
ALTER COLUMN REFERENCIA NVARCHAR(255);
UPDATE dbo.V_Semana
SET FACTURA = CONCAT_WS('-',SERIE,NFAC);
UPDATE dbo.V_Semana
SET DIA = DAY(FECHA);
ALTER TABLE dbo.V_Semana
ALTER COLUMN VENDIDO_POR NVARCHAR(255);
UPDATE dbo.V_Semana
SET MES = MONTH(FECHA);
UPDATE dbo.V_Semana
SET MES#TXT = DATENAME(MONTH, FECHA);
ALTER TABLE dbo.V_Semana
ALTER COLUMN AÑO INT;
UPDATE dbo.V_Semana
SET AÑO = YEAR(FECHA);
UPDATE dbo.V_Semana
SET D#SEM = DATENAME(WEEKDAY, FECHA);
UPDATE dbo.V_Semana
SET SEMANA = DATEPART(WEEK, FECHA);
UPDATE dbo.V_Semana
SET TRIMESTRE = CEILING(DATEPART(MONTH, FECHA) / 3.0);
UPDATE s
SET s.CLIENTE = c.R#SOCIAL
FROM dbo.V_Semana AS s
JOIN dbo.CLIENTES AS c ON s.COD#CLIENTE = c.COD#CLIENTE;
--COMERCIAL
ALTER TABLE dbo.V_Semana
ALTER COLUMN COMERCIAL NVARCHAR(255);
UPDATE s
SET s.COMERCIAL = c.NOMBRE_COMERCIAL
FROM dbo.V_Semana AS s
JOIN dbo.CLIENTES AS c ON s.COD#CLIENTE = c.COD#CLIENTE;
-- VENDIDO_POR
ALTER TABLE dbo.V_Semana
ALTER COLUMN VENDIDO_POR NVARCHAR(255);
UPDATE s
SET s.VENDIDO_POR = c.COMERCIAL
FROM dbo.V_Semana AS s
JOIN dbo.COMERCIALES AS c ON s.COD#COMERCIAL = c.COD;
UPDATE s
SET s.PC#UNIT = 
    CASE 
        WHEN REFERENCIA IS NULL AND s.FAMILIA = 45 THEN s.PVP / 2
        ELSE c.PC_UNITARIO
    END
FROM dbo.V_Semana AS s
LEFT JOIN dbo.ULTIMO_PC AS c ON s.REFERENCIA = c.ID_REF;
UPDATE dbo.V_Semana
SET PC#TTL = ROUND(PC#UNIT*CANTIDAD,3);
UPDATE dbo.V_Semana
SET BENEFICIO = ROUND((TTL / PC#TTL -1)*100,2);
UPDATE dbo.V_Semana
SET M = TTL-PC#TTL;
UPDATE s
SET s.PROVEEDOR = c.PROVE
FROM dbo.V_Semana AS s
JOIN dbo.COMPRAS_TOTALES AS c ON s.REFERENCIA = c.ID_REF;


-- METE LOS DATOS NUEVOS EN LA TABLA DE VENTAS TOTALES
INSERT INTO dbo.VENTAS_TOTALES
SELECT *
FROM dbo.V_Semana












